/**
 * @File Name          : T_MODEC_EnvioBoletim_Ctrl.cls
 * @Description        : Classe Controller relativa a integração do SAP / para criação do Boletim de medição
 * @Author             : Rafael Hadama
 * @Group              : 
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 05/11/2019 16:07:58
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    04/11/2019   Rafael Hadama     Initial Version
**/
public class T_MODEC_EnvioBoletim_Ctrl {
    
}