/**
 * @File Name          : T_MODEC_AppException.cls
 * @Description        : Classe do tipo Exception para o contexto da MODEC
 * @Author             : Rafael Hadama
 * @Group              : 
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 19/11/2019 20:33:08
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    19/11/2019   Rafael Hadama     Initial Version
**/
public class T_MODEC_AppException extends Exception{
    
}