@isTest
public with sharing class TestUtilTest {
    
    @isTest
    public static void testUtilTest()
    {
        /*Test.startTest();
        Vessel__c vessel = TestUtil.createVessel();
        VesselContract__c services = TestUtil.createVesselContractServices();
        VesselContract__c charter = TestUtil.createVesselContractCharter();
        Claim__c claim = TestUtil.createClaim('BOM');
        LetterGroup__c letterGroup = TestUtil.createLetterGroup();
        Letter__c letterSent = TestUtil.createLetterSent();
        Letter__c letterReceived = TestUtil.createLetterReceived();
        Letter__c letterReceived2 = TestUtil.createLetterReceived2();
        RDO__c rdo = TestUtil.createRDO();
        RDO__c rdo2 = TestUtil.createRDO2();
        LetterVesselAssociation__c letterVessel = TestUtil.createLVAssociation();
        VORVO__c vor = TestUtil.createVORVO();
        Test.stopTest(); */
    }

}