/**
 * @File Name          : TriggerException.cls
 * @Description        : 
 * @Author             : Mario Oliveira
 * @Group              : 
 * @Last Modified By   : Mario Oliveira
 * @Last Modified On   : 05/11/2019 18:36:51
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    05/11/2019   Mario Oliveira     Initial Version
**/
public class TriggerException extends Exception {
}